#spring配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/carbon?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456
  # redis
  redis:
    host: localhost
    port: 6379
#    password: 1234
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

#接口文档
knife4j:
  nacos:
    enable: true
    serviceUrl: localhost:8848/nacos


# 日志
logging:
  level:
    com.carbon.gate.mapper: debug
