rocketmq:
  name-server: localhost:9876
  producer:
    group: carbon-system
    send-message-timeout: 300000


#spring配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/carbon?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456
  #redis
  redis:
    host: localhost
    port: 6379
#    password: 1234
#  elasticsearch:
#    rest:
#      uris: localhost:9200

  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 日志
logging:
  level:
    com.carbon.trade.mapper: debug

